### ISSUE TITLE
Does this use structured header strings or tokens?

### ISSUE THREAD

**Issue by domenic** [nyaxt/bfcache-opt-in-header#1]
The example is

```
BFCache-Opt-In: unload
```

but the spec patch says

> If item is a string “unload”, set the document's unload salvageable opt-in state to true.

Probably the spec patch should use [tokens](https://httpwg.org/specs/rfc8941.html#token) instead of [strings](https://httpwg.org/specs/rfc8941.html#string); tokens feel more appropriate for this kind of limited set of potential values, instead of arbitrary strings.

**Comment by nyaxt** [comment]
Thanks! made it `token`
